// МАССИВ С ОБЪЕКТАМИ ИЗ КОТОРЫХ ТЯНУТЬСЯ ДАННЫЕ

const colorRu = {
  red: "крассный",
  yellow: "желтый",
  green: "зеленый",
  blue: "синий",
  pink: "розовый",
};

const salesItemObj = {
  status: "new",
  label: "НОВИНКА",
  category: "Платья",
  size: ["s", "m", "l", "xl", "xxxl"],
  name: "Крассное броское платье",
  url: "./img/items/item5.jpg",
  locatiion: "5 минут назад в интеренет магазине",
  price: "2000",
  color: ["red", "yellow", "green", "blue", "pink"],
};

const salesObj = [
  {
    status: "null",
    label: "",
    category: "Пальто",
    size: "M",
    name: "Красивое женское пальто розовое",
    url: "./img/items/item1.jpg",
    locatiion: "15 минут назад на Тверской",
    price: "5000",
  },
  {
    status: "new",
    label: "НОВИНКА",
    category: "Обувь",
    size: "все размеры",
    name: "Замшевые прикольные ботинки",
    url: "./img/items/item2.jpg",
    locatiion: "10 минут назад на Якиманке",
    price: "12000",
  },
  {
    status: "bestsales",
    label: "BESTSELLER",
    category: "Свитера",
    size: "L",
    name: "Мужской полосатый полувер",
    url: "./img/items/item3.jpg",
    locatiion: "18 минут назад на Петровке",
    price: "4000",
  },
  {
    status: "null",
    label: "",
    category: "Обувь",
    size: "все размеры",
    name: "Элегантные девичьи туфли",
    url: "./img/items/item4.jpg",
    locatiion: "8 минут назад на Киевской",
    price: "8000",
  },
  {
    status: "new",
    label: "НОВИНКА",
    category: "Платья",
    size: "S",
    name: "Крассное броское платье",
    url: "./img/items/item5.jpg",
    locatiion: "5 минут назад в интеренет магазине",
    price: "2000",
  },
  {
    status: "null",
    label: "",
    category: "Свитера",
    size: "XL",
    name: "Жилет, лучше для мужчины нет",
    url: "./img/items/item6.jpg",
    locatiion: "17 минут назад на Киевской",
    price: "5000",
  },
  {
    status: "bestsales",
    label: "BESTSELLER",
    category: "Одежда",
    size: "XXL",
    name: "Рубашка модного лесоруба",
    url: "./img/items/item7.jpg",
    locatiion: "11 минут назад на Петровке",
    price: "500",
  },
  {
    status: "hot",
    label: "ГОРЯЧЕЕ ПРЕДЛОЖЕНИЕ",
    category: "Одежда",
    size: "M",
    name: "Комбинезон джинсовый",
    url: "./img/items/item8.jpg",
    locatiion: "8 минут назад на Киевской",
    price: "1000",
  },
  {
    status: "top",
    label: "ЧАСТО СМОТРЯТ",
    category: "Украшения",
    size: "без размера",
    name: "Серьги",
    url: "./img/items/item9.jpg",
    locatiion: "12 минут назад на Тверской",
    price: "15000",
  },
  {
    status: "few",
    label: "ОСТАЛОСЬ МАЛО",
    category: "Пальто",
    size: "XL",
    name: "Чехол для хипстера. зимний",
    url: "./img/items/item10.jpg",
    locatiion: "16 минут назад на Якиманке",
    price: "3000",
  },
];
